# Generated by Django 5.2.7 on 2025-12-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
